name: 'Extract Artifacts'
description: 'Extracts artifacts'
inputs:
  path:
    description: 'path for extracted files'
    required: false
    default: '.'
  artifacts_url:
    description: 'url of archived artifacts'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ARTIFACTS_URL: ${{ inputs.artifacts_url }}
    PATH_FOR_EXTRACT: ${{ inputs.path }}
